### ISSUE TITLE
Include log files when CI specs fail

### ISSUE THREAD

**Issue by rakshasa** [axsh/openvnet#448]
Currently the CI only gives the initial flow table state before the specs run, that is not always enough information to determine the cause of the failure.

Look into dumping the log files for vnmgr, webapi and vna nodes after the specs have completed in the same manner as the flow tables. This should only be needed when specs fail.

**Comment by Metallion** [comment]
The first implementation of this broke the integration test since it relies on the exit code of the rspec subprocess. The way it was implemented, the tests read the log dump exit code which was always zero and assumed the tests were successful.

This feature needs to be re-implemented without that bug.

**Comment by Metallion** [comment]
I see this has been re-implemented.
